import Navbar from "./components/navbar";
import "./globals.css";
import { GeistSans } from "geist/font/sans";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${GeistSans.className} text-white`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
