import Navbar from "../components/navbar";
import "./globals.css";
import { GeistSans } from "geist/font/sans";
import WspBtn from "@/components/WspBtn";
export const metadata = {
  title: "Lumar Soft",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${GeistSans.className} text-white bg-black overflow-x-hidden`}
        style={{ position: "relative" }}
      >
        <Navbar />
        {children}

      <WspBtn/>
      </body>
    </html>
  );
}
